#baseURL = "https://example.com"
title = "Superjomn's blog"

theme = "papaya-theme"

[menu]


  [[menu.main]]
    identifier = "home"
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "post"
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 1


  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    pre = "info"
    url = "/posts/about/"
    weight = 3

[taxonomies]
  tag = "tags"

[params]
  authorName = "Chunwei Yan"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'abap'
    tabWidth = 4

