title = "Superjomn's blog"

theme = "papaya-theme"

[menu]


  [[menu.main]]
    identifier = "home"
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "Tech"
    name = "Tech"
    pre = "terminal"
    url = "/tags/tech"
    weight = 2

  [[menu.main]]
    identifier = "Life"
    name = "Life"
    pre = "coffee"
    url = "/tags/life"
    weight = 3

  [[menu.main]]
    identifier = "Archive"
    name = "Archive"
    pre = "archive"
    url = "/posts/"
    weight = 4

  [[menu.main]]
    identifier = "Tags"
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 5

  [[menu.main]]
    identifier = "About"
    name = "About"
    pre = "info"
    url = "/posts/about/"
    weight = 6

[taxonomies]
  tag = "tags"
  category = 'categories'

[params]
  authorName = "Chunwei Yan"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'friendly'
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
