#+title: Apple TV 折腾记
#+author: Chunwei Yan
#+date: 2023-04-18
#+hugo_tags: "life"
#+hugo_draft: false
#+toc: nil

由于房屋面积有限，我们的大厅一直没有安装电视。相反，我们使用了一个较大的LG 4K显示器作为娱乐中心，并搭配了两个巨大的Fyne落地音箱，效果不错。我们主要观看的节目是Netflix，晚上我们会和家人一起围在电脑旁边观看，感觉还不错。但是，将显示器用作电视存在一个问题，就是必须通过操作系统进行操作。由于我的职业是程序员，一旦接触电脑，就不由自主地敲击键盘，并且很容易进入工作模式，这对放松娱乐有些影响。

@@markdown:<!--more-->@@

因此，我开始考虑使用Apple TV作为我们的娱乐中心。我选择这个方案的原因如下：

1. 电视盒子本身可以提供完整的电视体验，操作相对简单，可以将电脑关闭以便更好地放松娱乐。
2. Apple TV可以安装Netflix、Youtube等应用程序，支持我们现有的娱乐方式。
3. 它具有HDMI接口，完美兼容我们现有的4K显示器，并且在未来升级成电视时也不会有问题。

现在，我们家的娱乐系统已经成为一套完整的影音系统。下面是我使用Apple TV的Recipe和我的考虑，供大家参考。

* Apple TV 本体

Apple TV 本体还是挺便宜的，可能 Apple 真正挣钱的是 Itunes 这类订阅服务吧，硬件只是附带的。我买的型号是 "Apple 苹果TV电视21/22新款 TV6 4K机顶盒子TV 7代 5.0 A15仿生电视盒子 苹果TV7代 128GB WIFI+网线版 美版"，价格是 1379人民币，你可以在淘宝或者京东找到。

* Wifi路由器

接下来需要有一款可以科学上网的 Wifi 路由器，这类 Wifi 由于要安装固件以及 ShadowSocks APP，因此一般配置要高一些也贵一些。

路由器一般要安装梅林固件，你最好了解下 [[https://zhuanlan.zhihu.com/p/205303870][梅林固件到底是什么-zhihu]]，只有华硕的一部分型号可以支持。

我选择的是 "华硕（ASUS）RT-AX86U双频5700M全千兆电竞路由无线路由器/一键性能加速/2.5G端口/WiFi6路由/PS5网络加速"，同样你可以在京东或者淘宝找到这款路由器，拼多多或者咸鱼上有可能找到更便宜的价格。
这是一款中高端的路由器，性能应该有点过剩了，我之前计划利用它自带的 USB 接口搭建一个简易的 NAS，但考虑到 4GB 的单个文件限制，最终没有实施；目前这是一个欠开发的，比较奢侈的路由器。

路由器连上网络后，需要刷梅林固件，这个网上教程很多，我参考比较多的是 [[https://www.youtube.com/watch?v=TKP3w1tlxL0][这个]]。 当然，前提是有个科学上网的 V&P&N，绑定到 WIFI 路由器中。

激活网络后，Apple TV 连上 WIFI，现在你应该已经能够激活和使用 Apple TV 了。

* 音响DAC的支持

虽然Apple TV支持AirPlay音源输出，但如果家里的音响是类似于HomePod或其他支持的播放器，只需要在设置里进行添加，就可以正常使用了。然而，由于我家里有一套音响系统，有专门的DAC，所以使用AirPlay这类有损的传输就比较可惜了。因此，我找到了一款HDMI拆分音源信息到光纤的转换器，名为“毕亚兹 HDMI2.0音频分离器线 4K/60HZ高清视频7.1光纤/同轴/3.5mm音频转换器笔记本机顶盒连接电视音响 ZH136”，可以完美支持AURALIC这类播放器的光纤输入。
注意，这里特定的参数才能支持 4K 视频的输出。转换后的音质与电脑的USB相比没有明显的差别，对于电视节目已经足够了吧。

* NAS系统
由于我有本地的音乐和视频想要组合到Apple TV的系统里，因此我额外花了不少银子搭建了一套NAS系统。如果您主要使用流媒体，这个基本上不是必需品，因为价格基本上比上面的组件加起来还要高一些。

之前我没有接触过NAS系统，并且也想降低不兼容的风险，所以我选择了群晖现成的NAS，DS220这款，外加希捷酷狼8TB的企业盘，从闲置的台式机上拆下来一个1TB的盘，七拼八凑跑起来了。目前这一套运行得不错，我经常使用自带的Download Station下载BT文件，目前有一半的节目是NAS提供的。

谈到NAS，Apple TV上的Infuse应用程序确实很实用，但是我尝试在App Store上付费时，似乎大陆的VISA无法使用。不过，总之还是通过各种折腾成功地使用了。

* 总结

总结下，除了 Apple TV 本体外，科学上网的 WIFI 路由器提供网络；NAS 提供本地的 BT 下载和视频服务；如果你要支持 DAC 那额外的 HDMI 拆光纤的转接口也是需要的。

折腾不易，且行珍惜。

老实说，这样一套操作下来，我觉得折腾的成本还是比较高的，从金钱到精力的投入都比较可观的，非技术宅折腾可能有点困难了。
